server:
  port: 8080
  servlet:
    context-path: /ScriptKill

spring:
  datasource:
    username: root
    password: TH@@2020
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.32.33.64:3306/tianheng_local?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false


