server:
  port: 8080
  servlet:
    context-path: /ScriptKill

spring:
  datasource:
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/scriptkill?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useSSL=false


